export function Spinner({ size = 24, className }: { size?: number; className?: string }) {
  return (
    <div className={`flex items-center justify-center${className ? ` ${className}` : ''}`}>
      <svg
        width={size}
        height={size}
        viewBox="0 0 54 54"
        preserveAspectRatio="xMidYMid"
        style={{
          shapeRendering: 'auto',
          display: 'block',
          background: 'none'
        }}
        xmlns="http://www.w3.org/2000/svg"
        className="animate-spin"
      >
        <title>Loading</title>
        <g>
          <g transform="rotate(0 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-100"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.9166666666666666s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(30 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-90"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.8333333333333334s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(60 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-75"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.75s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(90 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-60"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.6666666666666666s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(120 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-50"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.5833333333333334s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(150 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-40"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.5s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(180 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-30"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.4166666666666667s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(210 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-25"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.3333333333333333s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(240 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-20"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.25s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(270 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-10"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.16666666666666666s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(300 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-5"
            >
              <animate
                repeatCount="indefinite"
                begin="-0.08333333333333333s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g transform="rotate(330 27 27)">
            <rect
              fill="currentColor"
              height="14"
              width="6"
              ry="2.1"
              rx="2.1"
              y="0"
              x="24"
              className="opacity-0"
            >
              <animate
                repeatCount="indefinite"
                begin="0s"
                dur="1s"
                keyTimes="0;1"
                values="1;0"
                attributeName="opacity"
              ></animate>
            </rect>
          </g>
          <g></g>
        </g>
      </svg>
    </div>
  )
}
