/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as HomeIndexRouteImport } from './routes/_home.index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as AssessmentsAssessmentIdRouteImport } from './routes/assessments.$assessmentId'
import { Route as HomePatientsRouteImport } from './routes/_home.patients'
import { Route as HomeAssessmentsRouteImport } from './routes/_home.assessments'
import { Route as AssessmentsAssessmentIdTestTestTypeRouteImport } from './routes/assessments.$assessmentId_.test.$testType'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsAssessmentIdRoute = AssessmentsAssessmentIdRouteImport.update({
  id: '/assessments/$assessmentId',
  path: '/assessments/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomePatientsRoute = HomePatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAssessmentsRoute = HomeAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => HomeRoute,
} as any)
const AssessmentsAssessmentIdTestTestTypeRoute =
  AssessmentsAssessmentIdTestTestTypeRouteImport.update({
    id: '/assessments/$assessmentId_/test/$testType',
    path: '/assessments/$assessmentId/test/$testType',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/assessments': typeof HomeAssessmentsRoute
  '/patients': typeof HomePatientsRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/assessments/$assessmentId/test/$testType': typeof AssessmentsAssessmentIdTestTestTypeRoute
}
export interface FileRoutesByTo {
  '/assessments': typeof HomeAssessmentsRoute
  '/patients': typeof HomePatientsRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/': typeof HomeIndexRoute
  '/assessments/$assessmentId/test/$testType': typeof AssessmentsAssessmentIdTestTestTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/_home/assessments': typeof HomeAssessmentsRoute
  '/_home/patients': typeof HomePatientsRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/_home/': typeof HomeIndexRoute
  '/assessments/$assessmentId_/test/$testType': typeof AssessmentsAssessmentIdTestTestTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/patients'
    | '/assessments/$assessmentId'
    | '/patients/$patientId'
    | '/assessments/$assessmentId/test/$testType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assessments'
    | '/patients'
    | '/assessments/$assessmentId'
    | '/patients/$patientId'
    | '/'
    | '/assessments/$assessmentId/test/$testType'
  id:
    | '__root__'
    | '/_home'
    | '/_home/assessments'
    | '/_home/patients'
    | '/assessments/$assessmentId'
    | '/patients/$patientId'
    | '/_home/'
    | '/assessments/$assessmentId_/test/$testType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  AssessmentsAssessmentIdRoute: typeof AssessmentsAssessmentIdRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  AssessmentsAssessmentIdTestTestTypeRoute: typeof AssessmentsAssessmentIdTestTestTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$assessmentId': {
      id: '/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AssessmentsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/patients': {
      id: '/_home/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof HomePatientsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/assessments': {
      id: '/_home/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof HomeAssessmentsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/assessments/$assessmentId_/test/$testType': {
      id: '/assessments/$assessmentId_/test/$testType'
      path: '/assessments/$assessmentId/test/$testType'
      fullPath: '/assessments/$assessmentId/test/$testType'
      preLoaderRoute: typeof AssessmentsAssessmentIdTestTestTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HomeRouteChildren {
  HomeAssessmentsRoute: typeof HomeAssessmentsRoute
  HomePatientsRoute: typeof HomePatientsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAssessmentsRoute: HomeAssessmentsRoute,
  HomePatientsRoute: HomePatientsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  AssessmentsAssessmentIdRoute: AssessmentsAssessmentIdRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  AssessmentsAssessmentIdTestTestTypeRoute:
    AssessmentsAssessmentIdTestTestTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
