/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsCreateRouteImport } from './routes/patients/create'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients/$patientId/index'
import { Route as AssessmentsAssessmentIdIndexRouteImport } from './routes/assessments/$assessmentId/index'
import { Route as PatientsPatientIdEditRouteImport } from './routes/patients/$patientId/edit'
import { Route as AssessmentsAssessmentIdTestTestTypeRouteImport } from './routes/assessments/$assessmentId/test/$testType'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsCreateRoute = PatientsCreateRouteImport.update({
  id: '/patients/create',
  path: '/patients/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/patients/$patientId/',
  path: '/patients/$patientId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsAssessmentIdIndexRoute =
  AssessmentsAssessmentIdIndexRouteImport.update({
    id: '/assessments/$assessmentId/',
    path: '/assessments/$assessmentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientsPatientIdEditRoute = PatientsPatientIdEditRouteImport.update({
  id: '/patients/$patientId/edit',
  path: '/patients/$patientId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsAssessmentIdTestTestTypeRoute =
  AssessmentsAssessmentIdTestTestTypeRouteImport.update({
    id: '/assessments/$assessmentId/test/$testType',
    path: '/assessments/$assessmentId/test/$testType',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients/create': typeof PatientsCreateRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/assessments/$assessmentId/': typeof AssessmentsAssessmentIdIndexRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/assessments/$assessmentId/test/$testType': typeof AssessmentsAssessmentIdTestTestTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patients/create': typeof PatientsCreateRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdIndexRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/assessments/$assessmentId/test/$testType': typeof AssessmentsAssessmentIdTestTestTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patients/create': typeof PatientsCreateRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/assessments/$assessmentId/': typeof AssessmentsAssessmentIdIndexRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/assessments/$assessmentId/test/$testType': typeof AssessmentsAssessmentIdTestTestTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patients/create'
    | '/patients/$patientId/edit'
    | '/assessments/$assessmentId/'
    | '/patients/$patientId/'
    | '/assessments/$assessmentId/test/$testType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patients/create'
    | '/patients/$patientId/edit'
    | '/assessments/$assessmentId'
    | '/patients/$patientId'
    | '/assessments/$assessmentId/test/$testType'
  id:
    | '__root__'
    | '/'
    | '/patients/create'
    | '/patients/$patientId/edit'
    | '/assessments/$assessmentId/'
    | '/patients/$patientId/'
    | '/assessments/$assessmentId/test/$testType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientsCreateRoute: typeof PatientsCreateRoute
  PatientsPatientIdEditRoute: typeof PatientsPatientIdEditRoute
  AssessmentsAssessmentIdIndexRoute: typeof AssessmentsAssessmentIdIndexRoute
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
  AssessmentsAssessmentIdTestTestTypeRoute: typeof AssessmentsAssessmentIdTestTestTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/create': {
      id: '/patients/create'
      path: '/patients/create'
      fullPath: '/patients/create'
      preLoaderRoute: typeof PatientsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$assessmentId/': {
      id: '/assessments/$assessmentId/'
      path: '/assessments/$assessmentId'
      fullPath: '/assessments/$assessmentId/'
      preLoaderRoute: typeof AssessmentsAssessmentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/edit': {
      id: '/patients/$patientId/edit'
      path: '/patients/$patientId/edit'
      fullPath: '/patients/$patientId/edit'
      preLoaderRoute: typeof PatientsPatientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$assessmentId/test/$testType': {
      id: '/assessments/$assessmentId/test/$testType'
      path: '/assessments/$assessmentId/test/$testType'
      fullPath: '/assessments/$assessmentId/test/$testType'
      preLoaderRoute: typeof AssessmentsAssessmentIdTestTestTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientsCreateRoute: PatientsCreateRoute,
  PatientsPatientIdEditRoute: PatientsPatientIdEditRoute,
  AssessmentsAssessmentIdIndexRoute: AssessmentsAssessmentIdIndexRoute,
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
  AssessmentsAssessmentIdTestTestTypeRoute:
    AssessmentsAssessmentIdTestTestTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
